version: "3.9"
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomdb
    ports:
      - "3306:3306"
    volumes:
      - ./assets/ecomdb.sql:/docker-entrypoint-initdb.d/ecomdb.sql:ro

  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - database
